version: '3'
services: 
    db: 
        image: 'postgres:latest'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 99862446
            POSTGRES_DB: zoo
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"